### PR TITLE
Disable application menu

### PR DESCRIPTION
**Pull request by lcarva**
Also modified spaces to tabs to keep parity with rest of file.

### CODE REVIEW

**Comment by xPaw** [comment]
Thanks!

Are these PRs on behalf of the company or your own?

**Comment by lcarva** [comment]
You're welcome! I have been running thelounge for a few weeks and really like it!
I wanted it to run it locally and found it awkward to always have to start it in the background.
Eventually I came across this project which makes the UX for my use case much better.

> Are these PRs on behalf of the company or your own?

These are on my behalf.

**Comment by xPaw** [comment]
> I wanted it to run it locally and found it awkward to always have to start it in the background.

You can make an app shortcut in Chrome, so that it behaves like a standalone app. Have you tried that?

**Comment by lcarva** [comment]
> You can make an app shortcut in Chrome, so that it behaves like a standalone app. Have you tried that?

I have not, but that would still require something to start thelounge on the background right? I'm definitely trying to avoid that. My goal is to only have thelounge running when I'm actually using it. Otherwise, when I switch networks things get wonky and I may lose some messages.

**Comment by xPaw** [comment]
Ah yes, you would need to run the server side separately if you're not hosting it anywhere. You definitely get more benefits if you host lounge on a server (history, multiple devices, etc).

**Comment by xPaw** [comment]
@lcarva Since you're actually using this electron app, do you want to look into further maintaining it? I could add you as a contributor to the repo.

A quite big problem currently exists that it creates an user account with hard coded password.

**Comment by lcarva** [comment]
> Since you're actually using this electron app, do you want to look into further maintaining it? I could add you as a contributor to the repo.
> 
> A quite big problem currently exists that it creates an user account with hard coded password.

Sure, I could look into it.

**Comment by astorije** [comment]
Does that mean the electron app would start the server as well? That would remove one of the main features (if not _the_ main feature) of The Lounge, which is that it stays connected 24/7, like a bouncer / any other chat application.

Or could we make it connect to a server URL instead? That would be soooo cool (but I know it might come with a world of pain to implement).

**Comment by xPaw** [comment]
@astorije, that's what this electron app did since beginning, hence the experiment. You don't need a standalone electron app to use a hosted server.

**Comment by astorije** [comment]
@xPaw not sure what you mean by "that's what this electron app did since beginning". Do you mean that since the beginning this app embeds the server, or connects to a hosted server?

**Pull request merged**
